# Generated by Django 2.2.15 on 2020-09-12 10:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0027_customer_date_updated")]

    operations = [migrations.RemoveField(model_name="sources", name="endpoint_id")]
