# Generated by Django 3.1.8 on 2021-05-03 13:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0043_apply_turbo_schema_clone_func")]

    operations = [
        migrations.AddField(
            model_name="tenant", name="schema_create_running", field=models.BooleanField(default=False)
        ),
        migrations.AddField(model_name="tenant", name="schema_created", field=models.BooleanField(default=False)),
        migrations.RunSQL(
            """
ALTER TABLE api_tenant ALTER COLUMN schema_create_running SET DEFAULT false;
ALTER TABLE api_tenant ALTER COLUMN schema_created SET DEFAULT false;
"""
        ),
    ]
