# Generated by Django 2.2.15 on 2020-09-16 20:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0137_partitioned_tables_triggers")]

    operations = [
        migrations.RunSQL(
            """
                ALTER TABLE reporting_awstags_summary_values_mtm ALTER COLUMN id TYPE bigint;
                ALTER TABLE reporting_azuretags_summary_values_mtm ALTER COLUMN id TYPE bigint;
                ALTER TABLE reporting_ocpusagepodlabel_summary_values_mtm ALTER COLUMN id TYPE bigint;
                ALTER TABLE reporting_ocpstoragevolumelabel_summary_values_mtm ALTER COLUMN id TYPE bigint;

            """
        )
    ]
