# Generated by Django 3.1.8 on 2021-05-06 20:19
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0176_update_aws_enabled_keys")]

    operations = []
