# Generated by Django 3.1.8 on 2021-05-06 20:19
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0177_auto_20210506_1650")]

    operations = [
        migrations.RunSQL(
            """
alter table reporting_ocpallcostlineitem_daily_summary
  add column summary_level char(1);
"""
        ),
        migrations.RunSQL(
            """
alter table reporting_ocpusagelineitem_daily_summary
  add column summary_level char(1);
"""
        ),
        migrations.RunSQL(
            """
alter table reporting_gcpcostentrylineitem_daily_summary
  add column summary_level char(1);
"""
        ),
        migrations.RunSQL(
            """
alter table reporting_azurecostentrylineitem_daily_summary
  add column summary_level char(1);
"""
        ),
        migrations.RunSQL(
            """
alter table reporting_awscostentrylineitem_daily_summary
  add column summary_level char(1);
"""
        ),
    ]
