# Generated by Django 3.1.12 on 2021-06-14 18:04
import pkgutil

import django.contrib.postgres.fields.jsonb
from django.db import connection
from django.db import migrations
from django.db import models


def add_ocp_cost_views(apps, schema_editor):
    """Create the OCP Materialized views from files."""
    version = "_20210615"
    for view in ("", "_by_node", "_by_project"):
        view_sql = pkgutil.get_data(
            "reporting.provider.ocp", f"sql/views/reporting_ocp_cost_summary{view}{version}.sql"
        )
        view_sql = view_sql.decode("utf-8")
        with connection.cursor() as cursor:
            cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0179_matview_tags_hash")]

    operations = [
        # TODO: Find answers for these as far of how migrating to distributed cost should roll out
        #
        # One: We may want to delete the rows that have a supplementary or infrastructure
        # monthly cost filled in before we drop and readd. However, those may be cleaned up
        # if a cost model update is run.
        #
        # Two: We may need to trigger a cost model update somehow for our customers with existing cost
        # models.
        migrations.RunSQL(
            """
                DROP INDEX IF EXISTS ocp_cost_summary;
                DROP MATERIALIZED VIEW IF EXISTS reporting_ocp_cost_summary;
                DROP INDEX IF EXISTS ocp_cost_summary_by_node;
                DROP MATERIALIZED VIEW IF EXISTS reporting_ocp_cost_summary_by_node;
                DROP INDEX IF EXISTS ocp_cost_summary_by_project;
                DROP MATERIALIZED VIEW IF EXISTS reporting_ocp_cost_summary_by_project;

                ALTER TABLE reporting_ocpusagelineitem_daily_summary DROP COLUMN supplementary_monthly_cost;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN supplementary_monthly_cost jsonb;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary DROP COLUMN infrastructure_monthly_cost;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN infrastructure_monthly_cost jsonb;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN infrastructure_project_monthly_cost jsonb;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN supplementary_project_monthly_cost jsonb;
            """
        ),
        migrations.RunPython(add_ocp_cost_views),
    ]
