# Generated by Django 3.1.12 on 2021-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0179_matview_tags_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpcostentrylineitem',
            name='partition_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gcpcostentrylineitemdaily',
            name='partition_date',
            field=models.DateTimeField(null=True),
        ),
    ]
